### ISSUE TITLE
Some questions about the code of DP mechanism

### ISSUE THREAD

**Issue by scottshufe** [AI-secure/DP-GCN#3]
I have some questions about the DP code, such as:
1. Maybe these two lines
https://github.com/AI-secure/LinkTeller/blob/d067ad76f254f26bd12a87e1be4467f508a5151d/worker.py#L229
https://github.com/AI-secure/LinkTeller/blob/d067ad76f254f26bd12a87e1be4467f508a5151d/worker.py#L230
should be: 
```
indice_1 = entry[np.where(dig_1 == 1)]
indice_0 = entry[np.where(dig_1 == 0)]
```
2. It is hard for me to understand the code of LapGraph https://github.com/AI-secure/LinkTeller/blob/d067ad76f254f26bd12a87e1be4467f508a5151d/worker.py#L281 which is much different from the Algorithm. Especially, what dose the n_splits stand for?

**Comment by ghost** [comment]
1. The code is correct. Please refer to the below documents/tutorials to understand the usage of np.where() with only a condition.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

> When only condition is provided, this function is a shorthand for np.asarray(condition).nonzero().

https://www.digitalocean.com/community/tutorials/python-numpy-where

> 2. Using numpy.where() with only a condition

2. ``n_splits`` is to help alleviate the computational cost, using an idea similar to divide-and-conquer. E.g., instead of selecting top 10 elements from a 100M size array directly, we first split the 100M size array into 100 1M size arrays, selecting top 10 elements from each array (and therefore obtain an array of length 100x10=1000), and finally selecting top 10 elements from this 1000 size array. The cost is much lower.

Hope that helps.

Best,
Fan

**Comment by scottshufe** [comment]
Thanks for your reply.
Best wishes.
